return {
  ensure_installed = {
    'bash',
    'css',
    'dockerfile',
    'graphql',
    'javascript',
    'jsdoc',
    'json',
    'jsonc',
    'lua',
    'tsx',
    'typescript',
    'vim',
    'yaml',
  },
  highlight = { enabled = true },
  incremental_selection = { enabled = true },
  textobjects = { enabled = true },
}
