# First remove *all* keybindings
# unbind-key -a
# Now reinsert all the regular tmux keys
bind ^X lock-server
bind ^C new-window -c "$HOME"
bind ^N new-window -c "#{pane_current_path}"
bind ^D detach
bind * list-clients

bind H previous-window
bind L next-window

bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind z resize-pane -Z
bind ^L refresh-client
bind l refresh-client
bind | split-window
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind '"' choose-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D
bind S choose-session
bind K send-keys "clear"\; send-keys "Enter"
bind-key -T copy-mode-vi v send-keys -X begin-selection

set -g default-command fish
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
set -g mouse on
set -g pane-border-style 'fg=brightblack,bg=default'
set -g window-style 'dim'
set -g window-active-style 'default'
setw -g mode-keys vi

set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_number_position 'right'
set -g @catppuccin_window_text '#T'
set -g @catppuccin_window_current_text ' #W#{?window_zoomed_flag, 󰁌,} '
set -g @catppuccin_window_flags 'none'
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_left_separator ""
run '~/.config/tmux/plugins/catppuccin/catppuccin.tmux'

set -g status-left-length 100
set -g status-right-length 100
set -g status-left ''
set -g status-right '#{E:@catppuccin_status_session}#{E:@catppuccin_status_directory}'

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'

# tmux-thumbs
set -g @thumbs-command 'echo -n {} | pbcopy'

# Initialize TPM (must be at the very end)
run '~/.config/tmux/plugins/tpm/tpm'
