[user]
name = "Miquel de Domingo"
email = "miquelddg@gmail.com"

[ui]
editor = "nvim"
color = "auto"
default-command = "log"

[signing]
backend = "ssh"
behavior = "own"
key = "~/.ssh/github.pub"

[[--scope]]
--when.workspaces = ["~/Documents/work"]
[--scope.user]
email = "miquel.de.domingo@restream.io"
[--scope.signing]
backend = "ssh"
behavior = "own"
key = "~/.ssh/restream.pub"
