version: 2
log-level: 1
root-markers:
  - .git/
  - package.json

tools:
  stylua: &stylua
    format-command: "stylua -s --color Never -"
    format-stdin: true
    require-marker: true
    root-markers:
      - stylua.toml
      - .stylua.toml

  prettier: &prettier
    format-command: >
      prettierd --stdin --stdin-filepath ${INPUT}
    format-stdin: true
    format-can-range: true
    require-marker: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml

  eslint: &eslint
    format-command: "eslint --fix --stdin --stdin-filename ${INPUT}"
    format-stdin: true
    require-marker: true
    root-markers:
      - .eslintrc
      - .eslintrc.js
      - eslintrc.config.js

  fish_indent: &fish_indent
    format-command: "fish_indent"
    format-stdin: true

  fish_diagnostics: &fish_diagnostics
    lint-command: "fish --no-execute ${INPUT}"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - "%.%#(line %l): %m"

  actionlint-lint: &actionlint-lint
    prefix: actionlint
    lint-command: "bash -c \"[[ '${INPUT}' =~ \\\\.github/workflows/ ]]\" && actionlint -oneline -no-color -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    root-markers:
      - .github

languages:
  # lua
  lua:
    - <<: *stylua

  # web
  ## markup
  html:
    - <<: *eslint
    - <<: *prettier
  svelte:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  javascript.jsx:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  typescript.tsx:
    - <<: *eslint
    - <<: *prettier
  ## styles
  css:
    - <<: *eslint
    - <<: *prettier
  scss:
    - <<: *eslint
    - <<: *prettier
  less:
    - <<: *eslint
    - <<: *prettier
  ## scripts
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  ## other
  graphql:
    - <<: *eslint
    - <<: *prettier
  handlebars:
    - <<: *eslint
    - <<: *prettier
  markdown:
    - <<: *eslint
    - <<: *prettier
  markdown.mdx:
    - <<: *eslint
    - <<: *prettier

  # config
  json:
    - <<: *eslint
    - <<: *prettier
  jsonc:
    - <<: *eslint
    - <<: *prettier
  json5:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *eslint
    - <<: *prettier
    - <<: *actionlint-lint

  # shell
  fish:
    - <<: *fish_diagnostics
    - <<: *fish_indent
