return {
  {
    'catppuccin/nvim',
    lazy = true,
    ---@param opts CatppuccinOptions
    config = function(opts)
      opts.color_overrides = {
        macchiato = {
          rosewater = '#efc9c2',
          flamingo = '#ebb2b2',
          pink = '#f2a7de',
          mauve = '#b889f4',
          red = '#ea7183',
          maroon = '#ea838c',
          peach = '#f39967',
          yellow = '#eaca89',
          green = '#96d382',
          teal = '#78cec1',
          sky = '#91d7e3',
          sapphire = '#68bae0',
          blue = '#739df2',
          lavender = '#a0a8f6',
          text = '#b5c1f1',
          subtext1 = '#a6b0d8',
          subtext0 = '#959ec2',
          overlay2 = '#848cad',
          overlay1 = '#717997',
          overlay0 = '#63677f',
          surface2 = '#505469',
          surface1 = '#3e4255',
          surface0 = '#2c2f40',
          base = '#1a1c2a',
          mantle = '#141620',
          crust = '#0e0f16',
        },
      }
      opts.custom_highlights = function(C)
        return {
          CmpItemKindSnippet = { fg = C.base, bg = C.mauve },
          CmpItemKindKeyword = { fg = C.base, bg = C.red },
          CmpItemKindText = { fg = C.base, bg = C.teal },
          CmpItemKindMethod = { fg = C.base, bg = C.blue },
          CmpItemKindConstructor = { fg = C.base, bg = C.blue },
          CmpItemKindFunction = { fg = C.base, bg = C.blue },
          CmpItemKindFolder = { fg = C.base, bg = C.blue },
          CmpItemKindModule = { fg = C.base, bg = C.blue },
          CmpItemKindConstant = { fg = C.base, bg = C.peach },
          CmpItemKindField = { fg = C.base, bg = C.green },
          CmpItemKindProperty = { fg = C.base, bg = C.green },
          CmpItemKindEnum = { fg = C.base, bg = C.green },
          CmpItemKindUnit = { fg = C.base, bg = C.green },
          CmpItemKindClass = { fg = C.base, bg = C.yellow },
          CmpItemKindVariable = { fg = C.base, bg = C.flamingo },
          CmpItemKindFile = { fg = C.base, bg = C.blue },
          CmpItemKindInterface = { fg = C.base, bg = C.yellow },
          CmpItemKindColor = { fg = C.base, bg = C.red },
          CmpItemKindReference = { fg = C.base, bg = C.red },
          CmpItemKindEnumMember = { fg = C.base, bg = C.red },
          CmpItemKindStruct = { fg = C.base, bg = C.blue },
          CmpItemKindValue = { fg = C.base, bg = C.peach },
          CmpItemKindEvent = { fg = C.base, bg = C.blue },
          CmpItemKindOperator = { fg = C.base, bg = C.blue },
          CmpItemKindTypeParameter = { fg = C.base, bg = C.blue },
          CmpItemKindCopilot = { fg = C.base, bg = C.teal },
        }
      end
    end,
  },
}
