return {
  Normal = { fg = '#ABB2BF', bg = 'black' },
  StatusLineNC = { fg = '#ABB2BF' },
  DashboardCenter = { fg = '#ABB2BF' },
  DashboardFooter = { fg = '#ABB2BF' },
  DashboardHeader = { fg = '#ABB2BF' },
  DashboardShortcut = { fg = '#ABB2BF' },
  IndentBlanklineChar = { fg = '#3F4854' },
  Delimiter = { fg = '#ABB2BF' },
  TSPunctDelimiter = { fg = '#ABB2BF' },
  TSPunctBracket = { fg = '#ABB2BF' },
  TSPunctSpecial = { fg = '#ABB2BF' },
  TSAttribute = { fg = '#E06C75' },
  TSField = { fg = '#E06C75' },
  TSSymbol = { fg = '#E5C07B' },
  TSNamespace = { fg = '#E5C07B' },
  TSProperty = { fg = '#E06C75' },
  TSConstant = { fg = '#D19A66' },
  TSTagAttribute = { fg = '#E5C07B' },
}
